function out = exportGrBody(xtilde, debugData, endAtFirstNaN)
    % Export output of LG CEKF to grBody class
    %
    % :param xtilde: initial state in the GFR
    % :param debugData: initial covariance
    % :param endAtFirstNaN: [Optional] Boolean. If true, end at first nan state. Default: true
    %
    % :returns: [estBody, estoutDebug] - output and output debug grBody class
    %
    % .. Author: - Luke Wicent Sy (GSBME, 2019 Nov 26)

    if nargin <= 2
        endAtFirstNaN = true;
    end
    if endAtFirstNaN
        idxEndIdx = find(any(isnan(xtilde.vec), 1), 1);
        if isempty(idxEndIdx)
            idx = 1:length(xtilde.vec(1,:));
        elseif idxEndIdx == 0
            idx = []; 
        else
            idx = 1:(idxEndIdx-1); 
        end
    else
        idx = 1:length(xtilde.vec(1,:));
    end

    out = pelib.grBody('name', 'est', 'posUnit', 'm', 'oriUnit', 'deg', ...
       'lnSymbol', '--', 'ptSymbol', 'o', 'frame', 'world', ...
       'xyzColor', {'r', 'g', 'b'}, 'fs', debugData.fs, ...
       'MIDPEL', squeeze(xtilde.W_T_PV(1:3,4,idx))', ...
       'LFEP', debugData.LFEP(idx, :), ...
       'LFEO', debugData.LFEO(idx, :), ...
       'LTIO', squeeze(xtilde.W_T_LS(1:3,4,idx))', ...
       'RFEP', debugData.RFEP(idx, :), ...
       'RFEO', debugData.RFEO(idx, :), ...
       'RTIO', squeeze(xtilde.W_T_RS(1:3,4,idx))', ...
       'qRPV', rotm2quat(xtilde.W_T_PV(1:3,1:3,idx)), ...
       'qLTH', debugData.qLTH(idx, :), ...
       'qRTH', debugData.qRTH(idx, :), ...
       'qLSK', rotm2quat(xtilde.W_T_LS(1:3,1:3,idx)), ...
       'qRSK', rotm2quat(xtilde.W_T_RS(1:3,1:3,idx)));

end